version: '3'

services:
  rabbit:
    image: rabbitmq:management
    ports:
      - "61613:61613"
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbit/enable_plugins:/etc/rabbitmq/enabled_plugins
